node {
   
    stage('pre-build') { 
        sh '''
            sudo rm -rf docker-java
        '''
        git 'https://github.com/kiladia123/docker-java.git'
       
    }
    stage('Build') {
        
                sh '''
                pwd
                cd docker-spring-boot
                mvn clean package
                sudo docker build -t alpha007 .
                '''
            
        
    }
   stage('push') {
        
        sh'''
               sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 714549394535.dkr.ecr.us-east-1.amazonaws.com 
                sudo docker tag alpha007:latest 714549394535.dkr.ecr.us-east-1.amazonaws.com/alpha007:latest
                sudo docker push 714549394535.dkr.ecr.us-east-1.amazonaws.com/alpha007:latest
                
                echo 'container push to ecr'
        '''
    }
    stage('run') {
        
        sh'''
                sudo docker stop alpha007 && sudo docker rm alpha007 
                sudo docker run --name alpha007 -d -p 8090:8080 -t alpha007:latest
                echo 'containers running'
        '''
    }
}
